.TH "lib/srcs Directory Reference" 3 "Thu Apr 9 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/srcs Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBget_next_line\&.c\fP"
.br
.ti -1c
.RI "file \fBmalloc_gen_list\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_fprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_malloc\&.c\fP"
.br
.ti -1c
.RI "file \fBnbr\&.c\fP"
.br
.ti -1c
.RI "file \fBop\&.c\fP"
.br
.ti -1c
.RI "file \fBstring\&.c\fP"
.br
.ti -1c
.RI "file \fBstring_compare\&.c\fP"
.br
.ti -1c
.RI "file \fBstring_copy\&.c\fP"
.br
.in -1c
