.TH "corewar/includes/aff.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/includes/aff.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmy_putuchar\fP (unsigned char c)"
.br
.ti -1c
.RI "int \fBmy_aff\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_aff (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 23 of file aff\&.c\&.
.SS "void my_putuchar (unsigned charc)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
