.TH "corewar/srcs/aff.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/srcs/aff.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'corewar\&.h'\fP
.br
\fC#include 'champion\&.h'\fP
.br
\fC#include 'string_compare\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'nbr\&.h'\fP
.br
\fC#include 'my_fprintf\&.h'\fP
.br
\fC#include 'my_malloc\&.h'\fP
.br
\fC#include 'gen_list\&.h'\fP
.br
\fC#include 'vm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_aff\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_aff (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 23 of file aff\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
