.TH "corewar/srcs/champion.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/srcs/champion.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include 'champion\&.h'\fP
.br
\fC#include 'string_compare\&.h'\fP
.br
\fC#include 'nbr\&.h'\fP
.br
\fC#include 'my_fprintf\&.h'\fP
.br
\fC#include 'my_malloc\&.h'\fP
.br
\fC#include 'gen_list\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBmy_champion_file\fP (\fBt_champion\fP *champion, const char *file)"
.br
.ti -1c
.RI "static int \fBmy_champion_parameters\fP (int argc, char **argv, int *i, \fBt_champion\fP *champion)"
.br
.ti -1c
.RI "int \fBmy_champion\fP (int argc, char **argv, int *i, \fBt_champion\fP *champion)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_champion (intargc, char **argv, int *i, \fBt_champion\fP *champion)"

.PP
Definition at line 103 of file champion\&.c\&.
.SS "static unsigned int my_champion_file (\fBt_champion\fP *champion, const char *file)\fC [static]\fP"

.PP
Definition at line 29 of file champion\&.c\&.
.SS "static int my_champion_parameters (intargc, char **argv, int *i, \fBt_champion\fP *champion)\fC [static]\fP"

.PP
Definition at line 66 of file champion\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
