.TH "asm/includes/check.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/includes/check.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_check_param\fP (\fBargs_type_t\fP type, char *param)"
.br
.ti -1c
.RI "int \fBmy_check_params\fP (int i, \fBop_t\fP *optodo, char **lexed_line)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_check_param (\fBargs_type_t\fPtype, char *param)"

.PP
Definition at line 21 of file check_param\&.c\&.
.SS "int my_check_params (inti, \fBop_t\fP *optodo, char **lexed_line)"

.PP
Definition at line 48 of file check_param\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
