.TH "asm/srcs/check_param.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/srcs/check_param.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'compile\&.h'\fP
.br
\fC#include 'my_fprintf\&.h'\fP
.br
\fC#include 'op\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_check_param\fP (\fBargs_type_t\fP type, char *param)"
.br
.ti -1c
.RI "int \fBmy_check_params\fP (int i, \fBop_t\fP *op, char **lexed_line)"
.br
.ti -1c
.RI "int \fBcheck_if_valid_label\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int check_if_valid_label (char *str)"

.PP
Definition at line 74 of file check_param\&.c\&.
.SS "int my_check_param (\fBargs_type_t\fPtype, char *param)"

.PP
Definition at line 21 of file check_param\&.c\&.
.SS "int my_check_params (inti, \fBop_t\fP *op, char **lexed_line)"

.PP
Definition at line 48 of file check_param\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
