.TH "corewar/includes/corewar.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/includes/corewar.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'champion\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBu_int_rev\fP"
.br
.ti -1c
.RI "union \fBu_int\fP"
.br
.ti -1c
.RI "struct \fBs_corewar\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_corewar\fP \fBt_corewar\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_corewar\fP		 \fBt_corewar\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
