.TH "asm/srcs/gen_list.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/srcs/gen_list.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'gen_list\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'string_compare\&.h'\fP
.br
\fC#include 'op\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_list\fP * \fBnew_list\fP (\fBt_list\fP *old, int num_a, int num_b, char *str)"
.br
.ti -1c
.RI "void \fBfree_list\fP (\fBt_list\fP *s)"
.br
.ti -1c
.RI "int \fBmy_strcmp_lab\fP (char *label, char *str)"
.br
.ti -1c
.RI "int \fBlist_finder\fP (\fBt_list\fP *s, char *label)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void free_list (\fBt_list\fP *s)"

.PP
Definition at line 47 of file gen_list\&.c\&.
.SS "int list_finder (\fBt_list\fP *s, char *label)"

.PP
Definition at line 91 of file gen_list\&.c\&.
.SS "int my_strcmp_lab (char *label, char *str)"

.PP
Definition at line 68 of file gen_list\&.c\&.
.SS "\fBt_list\fP* new_list (\fBt_list\fP *old, intnum_a, intnum_b, char *str)"

.PP
Definition at line 22 of file gen_list\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
