.TH "lib/includes/get_next_line.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/includes/get_next_line.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_char\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUF_SIZE\fP   (1)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_char\fP \fBt_char\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBget_next_line\fP (const int fd)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUF_SIZE   (1)"

.PP
Definition at line 14 of file get_next_line\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_char\fP		 \fBt_char\fP"

.SH "Function Documentation"
.PP 
.SS "char* get_next_line (const intfd)"

.PP
Definition at line 71 of file get_next_line\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
