.TH "asm/srcs/get_argv.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/srcs/get_argv.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'string_compare\&.h'\fP
.br
\fC#include 'my_fprintf\&.h'\fP
.br
\fC#include 'string_copy\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'op\&.h'\fP
.br
\fC#include 'compile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBget_fname\fP (char *fname, char *str)"
.br
.ti -1c
.RI "char * \fBget_quotes_comment\fP (const char *str, char ret[])"
.br
.ti -1c
.RI "char * \fBget_quotes_name\fP (const char *str, char ret[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* get_fname (char *fname, char *str)"

.PP
Definition at line 24 of file get_argv\&.c\&.
.SS "char* get_quotes_comment (const char *str, charret[])"

.PP
Definition at line 45 of file get_argv\&.c\&.
.SS "char* get_quotes_name (const char *str, charret[])"

.PP
Definition at line 79 of file get_argv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
