.TH "header_s" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
header_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <op\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmagic\fP"
.br
.ti -1c
.RI "char \fBprog_name\fP [\fBPROG_NAME_LENGTH\fP+1]"
.br
.ti -1c
.RI "int \fBprog_size\fP"
.br
.ti -1c
.RI "char \fBcomment\fP [\fBCOMMENT_LENGTH\fP+1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file op\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char comment[\fBCOMMENT_LENGTH\fP+1]"

.PP
Definition at line 87 of file op\&.h\&.
.SS "int magic"

.PP
Definition at line 83 of file op\&.h\&.
.SS "char prog_name[\fBPROG_NAME_LENGTH\fP+1]"

.PP
Definition at line 85 of file op\&.h\&.
.SS "int prog_size"

.PP
Definition at line 86 of file op\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
