.TH "corewar/includes/ldi.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/includes/ldi.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_sec_arg\fP (\fBt_champion\fP *champion, unsigned char **arena, char codage, int i)"
.br
.ti -1c
.RI "int \fBldi_reg\fP (\fBt_champion\fP *champion, unsigned char **arena, char codage)"
.br
.ti -1c
.RI "int \fBldi\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ldi (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 108 of file ldi\&.c\&.
.SS "int ldi_reg (\fBt_champion\fP *champion, unsigned char **arena, charcodage)"

.PP
Definition at line 45 of file ldi\&.c\&.
.SS "int my_sec_arg (\fBt_champion\fP *champion, unsigned char **arena, charcodage, inti)"

.PP
Definition at line 22 of file ldi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
