.TH "asm/includes/lexer.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/includes/lexer.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSEPARATOR_CHAR2\fP   ' '"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_add_all\fP (int *i, char *str, int *j, char **tabl)"
.br
.ti -1c
.RI "void \fBmy_add_param\fP (char *str, int *j, char **tabl, int i)"
.br
.ti -1c
.RI "char ** \fBall_in_tab_base\fP (char *str, int word)"
.br
.ti -1c
.RI "char ** \fBall_in_tab\fP (char *str)"
.br
.ti -1c
.RI "void \fBremove_str_in_tab\fP (char **tab, int x)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SEPARATOR_CHAR2   ' '"

.PP
Definition at line 14 of file lexer\&.h\&.
.SH "Function Documentation"
.PP 
.SS "char** all_in_tab (char *str)"

.PP
Definition at line 105 of file lexer\&.c\&.
.SS "char** all_in_tab_base (char *str, intword)"

.PP
Definition at line 78 of file lexer\&.c\&.
.SS "int my_add_all (int *i, char *str, int *j, char **tabl)"

.PP
Definition at line 17 of file lexer\&.c\&.
.SS "void my_add_param (char *str, int *j, char **tabl, inti)"

.PP
Definition at line 49 of file lexer\&.c\&.
.SS "void remove_str_in_tab (char **tab, intx)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
