.TH "asm/srcs/lexer.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/srcs/lexer.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'op\&.h'\fP
.br
\fC#include 'my_malloc\&.h'\fP
.br
\fC#include 'lexer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_add_all\fP (int *i, char *str, int *j, char **tabl)"
.br
.ti -1c
.RI "void \fBmy_init_nx\fP (int *n, int *x)"
.br
.ti -1c
.RI "void \fBmy_add_param\fP (char *str, int *j, char **tabl, int i)"
.br
.ti -1c
.RI "char ** \fBall_in_tab_base\fP (char *str, int word)"
.br
.ti -1c
.RI "char ** \fBall_in_tab\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char** all_in_tab (char *str)"

.PP
Definition at line 105 of file lexer\&.c\&.
.SS "char** all_in_tab_base (char *str, intword)"

.PP
Definition at line 78 of file lexer\&.c\&.
.SS "int my_add_all (int *i, char *str, int *j, char **tabl)"

.PP
Definition at line 17 of file lexer\&.c\&.
.SS "void my_add_param (char *str, int *j, char **tabl, inti)"

.PP
Definition at line 49 of file lexer\&.c\&.
.SS "void my_init_nx (int *n, int *x)"

.PP
Definition at line 43 of file lexer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
