.TH "lib/includes/my_malloc.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/includes/my_malloc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_glist\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_glist\fP \fBt_glist\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_glist\fP * \fBnew_glist\fP (\fBt_glist\fP *old, void *data)"
.br
.ti -1c
.RI "\fBt_glist\fP * \fBadd_glist_start\fP (\fBt_glist\fP *s, void *data)"
.br
.ti -1c
.RI "void \fBfree_glist\fP (\fBt_glist\fP *s)"
.br
.ti -1c
.RI "void * \fBmy_malloc\fP (const unsigned int size)"
.br
.ti -1c
.RI "void \fBmy_free\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_glist\fP \fBt_glist\fP"

.PP
Definition at line 14 of file my_malloc\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBt_glist\fP* add_glist_start (\fBt_glist\fP *s, void *data)"

.SS "void free_glist (\fBt_glist\fP *s)"

.PP
Definition at line 34 of file malloc_gen_list\&.c\&.
.SS "void my_free ()"

.PP
Definition at line 38 of file my_malloc\&.c\&.
.SS "void* my_malloc (const unsigned intsize)"

.PP
Definition at line 24 of file my_malloc\&.c\&.
.SS "\fBt_glist\fP* new_glist (\fBt_glist\fP *old, void *data)"

.PP
Definition at line 14 of file malloc_gen_list\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
