.TH "lib/srcs/nbr.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/srcs/nbr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'string\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_getnbr\fP (const char *str)"
.br
.ti -1c
.RI "char \fBmy_putnbr\fP (int nbr)"
.br
.ti -1c
.RI "unsigned int \fBmy_str_isnum\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_getnbr (const char *str)"

.PP
Definition at line 14 of file nbr\&.c\&.
.SS "char my_putnbr (intnbr)"

.PP
Definition at line 44 of file nbr\&.c\&.
.SS "unsigned int my_str_isnum (const char *str)"

.PP
Definition at line 61 of file nbr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
