.TH "op_s" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
op_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <op\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBmnemonique\fP"
.br
.ti -1c
.RI "char \fBnbr_args\fP"
.br
.ti -1c
.RI "\fBargs_type_t\fP \fBtype\fP [\fBMAX_ARGS_NUMBER\fP]"
.br
.ti -1c
.RI "char \fBcode\fP"
.br
.ti -1c
.RI "int \fBnbr_cycles\fP"
.br
.ti -1c
.RI "char * \fBcomment\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file op\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char code"

.PP
Definition at line 52 of file op\&.h\&.
.SS "char* comment"

.PP
Definition at line 54 of file op\&.h\&.
.SS "char* mnemonique"

.PP
Definition at line 49 of file op\&.h\&.
.SS "char nbr_args"

.PP
Definition at line 50 of file op\&.h\&.
.SS "int nbr_cycles"

.PP
Definition at line 53 of file op\&.h\&.
.SS "\fBargs_type_t\fP type[\fBMAX_ARGS_NUMBER\fP]"

.PP
Definition at line 51 of file op\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
