.TH "corewar/srcs/operation.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/srcs/operation.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'op\&.h'\fP
.br
\fC#include 'corewar\&.h'\fP
.br
\fC#include 'champion\&.h'\fP
.br
\fC#include 'string_compare\&.h'\fP
.br
\fC#include 'nbr\&.h'\fP
.br
\fC#include 'my_fprintf\&.h'\fP
.br
\fC#include 'my_malloc\&.h'\fP
.br
\fC#include 'gen_list\&.h'\fP
.br
\fC#include 'vm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBset_indirect\fP (\fBt_champion\fP *champion, int *nb, unsigned char **arena)"
.br
.ti -1c
.RI "static void \fBget_nb\fP (\fBt_champion\fP *champion, unsigned char **arena, int *nb, char codage)"
.br
.ti -1c
.RI "int \fBmy_and\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.ti -1c
.RI "int \fBmy_or\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.ti -1c
.RI "int \fBmy_xor\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void get_nb (\fBt_champion\fP *champion, unsigned char **arena, int *nb, charcodage)\fC [static]\fP"

.PP
Definition at line 42 of file operation\&.c\&.
.SS "int my_and (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 67 of file operation\&.c\&.
.SS "int my_or (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 89 of file operation\&.c\&.
.SS "int my_xor (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 111 of file operation\&.c\&.
.SS "static void set_indirect (\fBt_champion\fP *champion, int *nb, unsigned char **arena)\fC [static]\fP"

.PP
Definition at line 22 of file operation\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
