.TH "corewar/includes/operation.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/includes/operation.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_and\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.ti -1c
.RI "int \fBmy_or\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.ti -1c
.RI "int \fBmy_xor\fP (\fBt_champion\fP *champion, unsigned char **arena)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_and (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 67 of file operation\&.c\&.
.SS "int my_or (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 89 of file operation\&.c\&.
.SS "int my_xor (\fBt_champion\fP *champion, unsigned char **arena)"

.PP
Definition at line 111 of file operation\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
