.TH "asm/includes/process.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/includes/process.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'list_lab_in\&.h'\fP
.br
\fC#include 'op\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBprocess_line\fP (char **lexed_line, int fd_binary, int *fileoffset, \fBt_lateinfo\fP *info)"
.br
.ti -1c
.RI "int \fBproces_file\fP (char *str)"
.br
.ti -1c
.RI "void \fBdir_to_ind\fP (char **lines, \fBop_t\fP *op)"
.br
.ti -1c
.RI "int \fBdirsize\fP (\fBop_t\fP *op, int i)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dir_to_ind (char **lines, \fBop_t\fP *op)"

.SS "int dirsize (\fBop_t\fP *op, inti)"

.PP
Definition at line 100 of file process\&.c\&.
.SS "int proces_file (char *str)"

.PP
Definition at line 67 of file process\&.c\&.
.SS "int process_line (char **lexed_line, intfd_binary, int *fileoffset, \fBt_lateinfo\fP *info)"

.PP
Definition at line 30 of file process\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
