.TH "asm/srcs/remove_str_in_tab.c" 3 "Thu Apr 9 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/srcs/remove_str_in_tab.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBremove_str_in_tab\fP (char **tab, int x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void remove_str_in_tab (char **tab, intx)"

.PP
Definition at line 11 of file remove_str_in_tab\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
