.TH "s_char" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_char \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <get_next_line\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBcharacter\fP"
.br
.ti -1c
.RI "struct \fBs_char\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file get_next_line\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char character"

.PP
Definition at line 18 of file get_next_line\&.h\&.
.SS "struct \fBs_char\fP* next"

.PP
Definition at line 19 of file get_next_line\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
