.TH "s_champion" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_champion \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <champion\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBPROG_NAME_LENGTH\fP+1]"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "char \fBcomment\fP [\fBCOMMENT_LENGTH\fP+1]"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.ti -1c
.RI "int \fBaddress\fP"
.br
.ti -1c
.RI "unsigned char * \fBcode\fP"
.br
.ti -1c
.RI "int \fBlive\fP"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.ti -1c
.RI "int \fBis_waiting\fP"
.br
.ti -1c
.RI "int \fBwait_time\fP"
.br
.ti -1c
.RI "int \fBreg\fP [\fBREG_NUMBER\fP+1]"
.br
.ti -1c
.RI "int \fBcarry\fP"
.br
.ti -1c
.RI "struct \fBs_champion\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file champion\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int address"

.PP
Definition at line 23 of file champion\&.h\&.
.SS "int carry"

.PP
Definition at line 30 of file champion\&.h\&.
.SS "unsigned char* code"

.PP
Definition at line 24 of file champion\&.h\&.
.SS "char comment[\fBCOMMENT_LENGTH\fP+1]"

.PP
Definition at line 21 of file champion\&.h\&.
.SS "int is_waiting"

.PP
Definition at line 27 of file champion\&.h\&.
.SS "int live"

.PP
Definition at line 25 of file champion\&.h\&.
.SS "char name[\fBPROG_NAME_LENGTH\fP+1]"

.PP
Definition at line 19 of file champion\&.h\&.
.SS "struct \fBs_champion\fP* next"

.PP
Definition at line 31 of file champion\&.h\&.
.SS "int number"

.PP
Definition at line 22 of file champion\&.h\&.
.SS "int pc"

.PP
Definition at line 26 of file champion\&.h\&.
.SS "int reg[\fBREG_NUMBER\fP+1]"

.PP
Definition at line 29 of file champion\&.h\&.
.SS "int size"

.PP
Definition at line 20 of file champion\&.h\&.
.SS "int wait_time"

.PP
Definition at line 28 of file champion\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
