.TH "s_corewar" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_corewar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <corewar\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdump\fP"
.br
.ti -1c
.RI "int \fBnbr_champions\fP"
.br
.ti -1c
.RI "int \fBteam_live\fP [4]"
.br
.ti -1c
.RI "\fBt_champion\fP * \fBchampions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file corewar\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_champion\fP* champions"

.PP
Definition at line 34 of file corewar\&.h\&.
.SS "int dump"

.PP
Definition at line 31 of file corewar\&.h\&.
.SS "int nbr_champions"

.PP
Definition at line 32 of file corewar\&.h\&.
.SS "int team_live[4]"

.PP
Definition at line 33 of file corewar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
