.TH "s_glist" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_glist \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <my_malloc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "\fBt_glist\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBt_glist\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file my_malloc\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* data"

.PP
Definition at line 18 of file my_malloc\&.h\&.
.SS "\fBt_glist\fP* next"

.PP
Definition at line 19 of file my_malloc\&.h\&.
.SS "\fBt_glist\fP* prev"

.PP
Definition at line 20 of file my_malloc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
