.TH "s_latinfo" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_latinfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list_lab_in\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnbrinstruction\fP"
.br
.ti -1c
.RI "\fBt_list\fP * \fBlabel\fP"
.br
.ti -1c
.RI "\fBt_list\fP * \fBlabel_call\fP"
.br
.ti -1c
.RI "\fBt_list\fP * \fBindirect_call\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file list_lab_in\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_list\fP* indirect_call"

.PP
Definition at line 21 of file list_lab_in\&.h\&.
.SS "\fBt_list\fP* label"

.PP
Definition at line 19 of file list_lab_in\&.h\&.
.SS "\fBt_list\fP* label_call"

.PP
Definition at line 20 of file list_lab_in\&.h\&.
.SS "int nbrinstruction"

.PP
Definition at line 18 of file list_lab_in\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
