.TH "s_list" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gen_list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnum_value_a\fP"
.br
.ti -1c
.RI "int \fBnum_value_b\fP"
.br
.ti -1c
.RI "int \fBnum_value_c\fP"
.br
.ti -1c
.RI "char * \fBstr_value\fP"
.br
.ti -1c
.RI "\fBt_list\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBt_list\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file gen_list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_list\fP* next"

.PP
Definition at line 22 of file gen_list\&.h\&.
.SS "int num_value_a"

.PP
Definition at line 18 of file gen_list\&.h\&.
.SS "int num_value_b"

.PP
Definition at line 19 of file gen_list\&.h\&.
.SS "int num_value_c"

.PP
Definition at line 20 of file gen_list\&.h\&.
.SS "\fBt_list\fP* prev"

.PP
Definition at line 23 of file gen_list\&.h\&.
.SS "char* str_value"

.PP
Definition at line 21 of file gen_list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
