.TH "s_pos_info" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_pos_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <compile\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBwhereiam\fP"
.br
.ti -1c
.RI "int \fBto_cur_in\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file compile\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int to_cur_in"

.PP
Definition at line 24 of file compile\&.h\&.
.SS "int whereiam"

.PP
Definition at line 23 of file compile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
