.TH "s_ptr_fct" 3 "Thu Apr 9 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_ptr_fct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <the_game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "int(* \fBfc_pt\fP )(\fBt_corewar\fP *, int *, unsigned char **)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file the_game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int code"

.PP
Definition at line 18 of file the_game\&.h\&.
.SS "int(* fc_pt)(\fBt_corewar\fP *, int *, unsigned char **)"

.PP
Definition at line 19 of file the_game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
