.TH "lib/includes/string_copy.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/includes/string_copy.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strcpy\fP (const char *dest, const char *src)"
.br
.ti -1c
.RI "char * \fBmy_strncpy\fP (const char *dest, const char *src, const unsigned int n)"
.br
.ti -1c
.RI "char * \fBmy_strcat\fP (const char *dest, const char *src)"
.br
.ti -1c
.RI "char * \fBmy_strncat\fP (const char *dest, const char *src, const unsigned int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strcat (const char *dest, const char *src)"

.SS "char* my_strcpy (const char *dest, const char *src)"

.SS "char* my_strncat (const char *dest, const char *src, const unsigned intn)"

.SS "char* my_strncpy (const char *dest, const char *src, const unsigned intn)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
