.TH "lib/includes/string.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/includes/string.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBmy_putchar\fP (const char c)"
.br
.ti -1c
.RI "int \fBmy_strlen\fP (const char *str)"
.br
.ti -1c
.RI "int \fBmy_putstr\fP (const char *str)"
.br
.ti -1c
.RI "int \fBmy_putstr_error\fP (const char *str)"
.br
.ti -1c
.RI "int \fBmy_tablen\fP (char **tab)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char my_putchar (const charc)"

.PP
Definition at line 14 of file string\&.c\&.
.SS "int my_putstr (const char *str)"

.PP
Definition at line 53 of file string\&.c\&.
.SS "int my_putstr_error (const char *str)"

.PP
Definition at line 31 of file string\&.c\&.
.SS "int my_strlen (const char *str)"

.PP
Definition at line 19 of file string\&.c\&.
.SS "int my_tablen (char **tab)"

.PP
Definition at line 43 of file string\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
