.TH "lib/srcs/string_copy.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/srcs/string_copy.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'my_malloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strcpy\fP (char *dest, const char *src)"
.br
.ti -1c
.RI "char * \fBmy_strncpy\fP (char *dest, const char *src, const unsigned int n)"
.br
.ti -1c
.RI "char * \fBmy_strcat\fP (char *s1, const char *s2)"
.br
.ti -1c
.RI "char * \fBmy_strncat\fP (char *s1, const char *s2, const unsigned int nb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strcat (char *s1, const char *s2)"

.PP
Definition at line 47 of file string_copy\&.c\&.
.SS "char* my_strcpy (char *dest, const char *src)"

.PP
Definition at line 15 of file string_copy\&.c\&.
.SS "char* my_strncat (char *s1, const char *s2, const unsigned intnb)"

.PP
Definition at line 74 of file string_copy\&.c\&.
.SS "char* my_strncpy (char *dest, const char *src, const unsigned intn)"

.PP
Definition at line 31 of file string_copy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
