.TH "lib/includes/string_compare.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/includes/string_compare.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_strcmp\fP (const char *s1, const char *s2)"
.br
.ti -1c
.RI "int \fBmy_strncmp\fP (const char *s1, const char *s2, const unsigned int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_strcmp (const char *s1, const char *s2)"

.PP
Definition at line 14 of file string_compare\&.c\&.
.SS "int my_strncmp (const char *s1, const char *s2, const unsigned intn)"

.PP
Definition at line 35 of file string_compare\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
