.TH "corewar/includes/the_game.h" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/includes/the_game.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPC_OP_CODE\fP   (((*arena)[tmp->pc] - 1))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBlets_play\fP (\fBt_corewar\fP *corewar, int cycles, int backup_cycles, unsigned char **arena)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PC_OP_CODE   (((*arena)[tmp->pc] - 1))"

.PP
Definition at line 14 of file the_game\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int lets_play (\fBt_corewar\fP *corewar, intcycles, intbackup_cycles, unsigned char **arena)"

.PP
Definition at line 111 of file the_game\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
