.TH "u_int" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_int \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <corewar\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "char \fBc\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file corewar\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char c[4]"

.PP
Definition at line 26 of file corewar\&.h\&.
.SS "int i"

.PP
Definition at line 25 of file corewar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
