.TH "corewar/srcs/vm.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corewar/srcs/vm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'corewar\&.h'\fP
.br
\fC#include 'champion\&.h'\fP
.br
\fC#include 'string_compare\&.h'\fP
.br
\fC#include 'nbr\&.h'\fP
.br
\fC#include 'my_fprintf\&.h'\fP
.br
\fC#include 'my_malloc\&.h'\fP
.br
\fC#include 'gen_list\&.h'\fP
.br
\fC#include 'vm\&.h'\fP
.br
\fC#include 'the_game\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fBcheck\fP ()"
.br
.ti -1c
.RI "static void \fBset_empty\fP (\fBt_corewar\fP *corewar, unsigned char **arena)"
.br
.ti -1c
.RI "static int \fBset_arena\fP (\fBt_corewar\fP *corewar, unsigned char **arena)"
.br
.ti -1c
.RI "int \fBmy_vm\fP (\fBt_corewar\fP *corewar)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static int check ()\fC [static]\fP"

.PP
Definition at line 22 of file vm\&.c\&.
.SS "int my_vm (\fBt_corewar\fP *corewar)"

.PP
Definition at line 89 of file vm\&.c\&.
.SS "static int set_arena (\fBt_corewar\fP *corewar, unsigned char **arena)\fC [static]\fP"

.PP
Definition at line 63 of file vm\&.c\&.
.SS "static void set_empty (\fBt_corewar\fP *corewar, unsigned char **arena)\fC [static]\fP"

.PP
Definition at line 41 of file vm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
