.TH "asm/srcs/write_header.c" 3 "Sun Apr 12 2015" "Version 1.0" "Corewar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/srcs/write_header.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include 'op\&.h'\fP
.br
\fC#include 'list_lab_in\&.h'\fP
.br
\fC#include 'get_argv\&.h'\fP
.br
\fC#include 'compile\&.h'\fP
.br
\fC#include 'my_fprintf\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'string_copy\&.h'\fP
.br
\fC#include 'string_compare\&.h'\fP
.br
\fC#include 'my_malloc\&.h'\fP
.br
\fC#include 'get_next_line\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_name_comment\fP (char *line, \fBheader_t\fP *header, char *isdonename, char *isdonecom)"
.br
.ti -1c
.RI "int \fBput_in_be\fP (char *arg, int size)"
.br
.ti -1c
.RI "int \fBwrite_header_ext\fP (int fd_bin, int fd_champ, \fBheader_t\fP *header)"
.br
.ti -1c
.RI "int \fBwrite_header\fP (int fd_champ, int fd_bin)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int get_name_comment (char *line, \fBheader_t\fP *header, char *isdonename, char *isdonecom)"

.PP
Definition at line 30 of file write_header\&.c\&.
.SS "int put_in_be (char *arg, intsize)"

.PP
Definition at line 62 of file write_header\&.c\&.
.SS "int write_header (intfd_champ, intfd_bin)"

.PP
Definition at line 118 of file write_header\&.c\&.
.SS "int write_header_ext (intfd_bin, intfd_champ, \fBheader_t\fP *header)"

.PP
Definition at line 92 of file write_header\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Corewar from the source code\&.
